
spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  datasource:
    url: jdbc:mysql://localhost:3306/ex
    username: root
    password: 123456
    type:  com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  thymeleaf:
    enabled: true
    cache: false
  messages:
    basename: "messages/message"
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: seyed.ali.hejazi.35@gmail.com
    password: asleepsleep
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 80
BASE_PATH: "E:\\Newfolder"
hostname: localhost